server:
  port: 4001

spring:
  application:
    name: member-service

  data:
    mongodb:
      username: ""
      uri: mongodb://localhost:27017/legato-backend


eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
#      defaultZone: http://192.168.99.100:8761/eureka/